# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(blank=True, default='', max_length=100)),
                ('lastName', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('password', models.CharField(max_length=100)),
                ('profilePic', models.URLField(default='', max_length=500)),
                ('dateJoined', models.DateField(auto_now_add=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=1)),
                ('isPremiumUser', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('isVerified', models.BooleanField(default=True)),
                ('username', models.CharField(default='', max_length=100)),
                ('phoneNumber', models.CharField(blank=True, default='', max_length=20)),
                ('lastLogin', models.DateField(auto_now_add=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=1000)),
                ('userType', models.IntegerField(choices=[(0, 'Student'), (1, 'Business Man'), (2, 'Developer'), (3, 'Admins')])),
            ],
        ),
    ]
