# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rproperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('log', models.FloatField(default=0)),
                ('rid', models.IntegerField(default=0)),
                ('sqfeet', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
