# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rprediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oct_17', models.FloatField(default=0)),
                ('nov_17', models.FloatField(default=0)),
                ('dec_17', models.FloatField(default=0)),
                ('ppty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.rproperty')),
            ],
        ),
    ]
