# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('graphData', jsonfield.fields.JSONField(blank=True, null=True)),
                ('testAccuracy', models.FloatField(default=0)),
                ('testScore', models.FloatField(default=0)),
                ('modelPath', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='companyNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('news', models.CharField(max_length=15000)),
                ('sentimentPolarity', models.FloatField(blank=True, null=True)),
                ('sentimentSubjectivity', models.FloatField(blank=True, null=True)),
                ('companyDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_backend.company')),
            ],
        ),
        migrations.CreateModel(
            name='companyTweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('tweetInfo', models.CharField(max_length=2000)),
                ('retweets', models.IntegerField(blank=True, null=True)),
                ('sentimentPolarity', models.FloatField(blank=True, null=True)),
                ('sentimentSubjectivity', models.FloatField(blank=True, null=True)),
                ('companyDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_backend.company')),
            ],
        ),
        migrations.CreateModel(
            name='predictionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateField(auto_now_add=True)),
                ('predictions', jsonfield.fields.JSONField(blank=True, null=True)),
                ('companyDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_backend.company')),
            ],
        ),
        migrations.CreateModel(
            name='stockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('openPrice', models.FloatField(blank=True, null=True)),
                ('previousPrice', models.FloatField(blank=True, null=True)),
                ('lowPrice', models.FloatField(blank=True, null=True)),
                ('highPrice', models.FloatField(blank=True, null=True)),
                ('closePrice', models.FloatField(blank=True, null=True)),
                ('ltp', models.FloatField(blank=True, null=True)),
                ('turnover', models.CharField(blank=True, max_length=20)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('trades', models.FloatField(blank=True, null=True)),
                ('series', models.CharField(blank=True, max_length=20)),
                ('companyDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_backend.company')),
            ],
        ),
    ]
