# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mae',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='mse',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
