# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stock_backend', '0002_auto_20170703_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='testScore',
            new_name='testMAE',
        ),
        migrations.RemoveField(
            model_name='company',
            name='mae',
        ),
        migrations.RemoveField(
            model_name='company',
            name='mse',
        ),
        migrations.AddField(
            model_name='company',
            name='modelInfo',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='testMSE',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='series',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
