# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_backend', '0005_company_debt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='maxVal',
            new_name='ltp',
        ),
    ]
