# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=15000, null=True)),
                ('interestRate', models.FloatField(null=True)),
                ('website', models.URLField()),
            ],
        ),
    ]
