# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankInfoFD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('group', models.CharField(blank=True, max_length=250, null=True)),
                ('period', models.CharField(blank=True, max_length=350, null=True)),
                ('investmentCap', models.CharField(blank=True, max_length=400, null=True)),
                ('investorType', models.CharField(blank=True, max_length=50, null=True)),
                ('taxStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('interestRate', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='bankInfo',
        ),
    ]
